ARDUINO_DIR  = /home/mattis/.arduino-1.6.7/

TARGET       = main
ARDUINO_LIBS = 

MCU          = atmega328p
F_CPU        = 16000000

BOARD_TAG    = uno
ISP_PORT = /dev/ttyACM*

# Avrdude code
ARDUINO_PORT = /dev/ttyACM0
AVRDUDE_ARD_PROGRAMMER = arduino
AVRDUDE_ARD_BAUDRATE = 115200

include /home/mattis/.Arduino-Makefile/Arduino.mk


